var cfg = require("./knex-cfg").pg;
var knex = require("knex")(cfg);
var screen = require("./screen");

screen.clear();

// do the following, OR add debug: true to config to see SQL generated by KNEX
// var query = knex.select("title", "rating").from("book");
// var sql = query.toSQL();
// screen.write(sql)

knex.select("title", "rating").from("book").then(function(rows) {
  screen.write(rows);
})
.catch(function(err) {
  screen.write("Oops");
  screen.write(err);
})
.finally(function() {
  knex.destroy();
})
